{
  'targets': [
    {
      'target_name': 'agent',
      'type': 'static_library',
      'include_dirs': [ 'include' ],
      'variables': { 'packages': ['libsoup-2.4'] },
      'includes': [ '../../pkg-config.gypi' ],
      'cflags': [ '-fPIC' ],
      'ldflags': [ '-fPIC' ],
      'sources': [
         'download-agent-basic.c',
         'download-agent-client-mgr.c',
         'download-agent-debug.c',
         'download-agent-dl-info-util.c',
         'download-agent-dl-mgr.c',
         'download-agent-encoding.c',
         'download-agent-file.c',
         'download-agent-http-mgr.c',
         'download-agent-http-misc.c',
         'download-agent-http-msg-handler.c',
         'download-agent-http-queue.c',
         'download-agent-interface.c',
         'download-agent-mime-util.c',
         'download-agent-plugin-conf.c',
         'download-agent-plugin-libsoup.c',
         'download-agent-utils.c',
         'download-agent-utils-dl-id-history.c',
         'include/download-agent-basic.h',
         'include/download-agent-client-mgr.h',
         'include/download-agent-debug.h',
         'include/download-agent-defs.h',
         'include/download-agent-dl-info-util.h',
         'include/download-agent-dl-mgr.h',
         'include/download-agent-encoding.h',
         'include/download-agent-file.h',
         'include/download-agent-http-mgr.h',
         'include/download-agent-http-misc.h',
         'include/download-agent-http-msg-handler.h',
         'include/download-agent-http-queue.h',
         'include/download-agent-interface.h',
         'include/download-agent-mime-util.h',
         'include/download-agent-plugin-conf.h',
         'include/download-agent-plugin-http-interface.h',
         'include/download-agent-plugin-libsoup.h',
         'include/download-agent-pthread.h',
         'include/download-agent-type.h',
         'include/download-agent-utils-dl-id-history.h',
         'include/download-agent-utils.h',
      ],
    },
  ],
}
